config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'users#index'

end

app/models/permission.rb
class Permission < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :permissions

  scope :starts_with, ->(start) { where('name LIKE ?', "#{start}%") }
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  has_and_belongs_to_many :permissions
  validates :name, presence: true

  def all_permissions
    perms = Set.new(permissions)
    perms.merge(role.permissions) if role
    perms
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    render locals: local_parameters
  end

  def create
    actual_user = User.new(user_params)

    respond_to do |format|
      if actual_user.save
        format.html { redirect_to users_path, notice: ApplicationHelper::Constants::SUCCESS_NOTICE }
        format.js   do
          render locals: { success: true,
                           notice: ApplicationHelper::Constants::SUCCESS_NOTICE,
                           saved_user: actual_user }.merge!(local_parameters)
        end
        format.json { render json: actual_user, status: :created }
      else
        format.html { render 'index', locals: local_parameters(actual_user) }
        format.js   { render locals: { success: false }.merge!(local_parameters(actual_user)) }
        format.json { render json: actual_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to users_url
    else
      render 'index', locals: local_parameters(user)
    end
  end

  def edit
    user = User.find(params[:id])
    render 'index', locals: local_parameters(user)
  end

  private

  def local_parameters(actual_user = nil)
    { user: actual_user.nil? ? User.new : actual_user,
      all_user: User.all,
      roles: Role.all }
  end

  def user_params
    params.require(:user).permit(:name, :status, :role_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  module Constants
    SUCCESS_NOTICE = 'User was successfully created.'.freeze
    STATUS_OPTIONS = ['Status 1', 'Status 2'].freeze
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railstest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for user, remote: true do |f| %>

    <% if user.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(user.errors.count, "error") %> prohibited
            this user from being saved:
          </h3>
          <ul>
            <% user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :status %><br>
      <%= f.select(:status,
                   options_for_select(ApplicationHelper::Constants::STATUS_OPTIONS,
                                      selected:user.status),
                   include_blank: true) %>
    </p>

    <p>
      <%= f.label :role %><br>
      <%= f.select(:role_id,
                   options_from_collection_for_select(roles, :id, :name, user.role_id),
                   include_blank: true)%>
    </p>
    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/users/_user.html.erb
<li>
  <p>name:
    <%= link_to user.name, edit_user_path(user) %>
  </p>
  <p>role: <%= user.role.try(:name) %></p>
  <p>permissions:
    <% user.all_permissions.each do |permission| %>
      <span>
        <%= permission.name %>
      </span>
    <% end %>
  </p>
</li>

app/views/users/create.js.erb
<% if success %>
  $("<%= j(render 'user', user: saved_user) %>").appendTo("#users");
<% end %>
$("#notice").html("<%= notice %>");
$("#user-form").html("<%= j(render partial: 'form', locals: { user: user, roles: roles }) %>");

app/views/users/index.html.erb
<h1>Listing users</h1>

<ul id="users">
  <%= render all_user %>
</ul>

<h2>Add/edit user</h2>
<p id="notice"><%= notice %></p>
<div id="user-form">
  <%= render partial: 'form', locals: { user: user, roles: roles } %>
</div>